### ISSUE TITLE
Implement WebContainers to be used by live-editing generated sample

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-live-editing#19]
Currently, sample generation fails. Followed stuff need to be considered:

1) Stackblitz
StackBlitz now supports WebContainers and they recommend using it. Will add more links later.

2) CodeSandBox:
Need to have this resolved https://github.com/codesandbox/codesandbox-client/issues/6341 and also implement 1)

**Comment by dobromirts** [comment]
Live editing testing:
1. Clone Live Editing repository https://github.com/IgniteUI/igniteui-live-editing
2. Build the project and do 'npm link' in the generated 'lib' folder
3. Clone Angular Sample Repo https://github.com/IgniteUI/igniteui-angular-samples and 
Angular DV Sample  http://tfs.infragistics.local:8080/tfs/Engineering/IgInternalApplicationsGit/IgInternalApplicationsGit%20Team/_git/angular-samples-dv
4. Link the live editing to angular samples and angular dv samples projects 'npm link igniteui-live-editing'
5. Clone https://github.com/IgniteUI/igniteui-docfx-template and https://github.com/IgniteUI/igniteui-docfx
6. Build igniteui-docfx-template and do 'npm link' in the generated 'dist' folder
7. Link igniteui-docfx-template in igniteui-docfx project 'npm link igniteui-docfx-template'
8. Start igniteui-angular-samples with "npm run start:app-lob:live-editing" or "npm run start:live-editing" and start the igniteui-docfx project
